package com.aliucord.plugins.translate.strings

object StringsZh : IStrings {
    override val pluginName           = "增强翻译"

    override val actionTranslate      = "翻译此消息"
    override val actionShowOriginal   = "显示原文"
    override val actionRetranslate    = "重新翻译此消息"
    override val actionToggleAuto     = "自动翻译此频道"
    override val actionDisableAuto    = "关闭自动翻译"
    override val actionResumeAuto     = "恢复自动翻译"

    override val toastTranslated      = "消息已翻译"
    override val toastAutoPaused      = "翻译失败次数过多，已暂停自动翻译。点击恢复。"
    override val toastAutoResumed     = "已恢复自动翻译"
    override val toastAutoDisabled    = "已关闭自动翻译"
    override val toastAutoBatchStart       = "开始批量翻译…"
    override val toastAutoBatchRequesting  = "正在请求翻译后端（"
    override val toastAutoBatchRequestingEnd = " 条）…"
    override val toastAutoBatchDonePrefix  = "本批 "
    override val toastAutoBatchDoneSuffix  = " 条翻译完成"
    override val toastAutoBatchDoneFallbackPrefix = "（"
    override val toastAutoBatchDoneFallbackMid = " 条降级 Google）"
    override val toastBackendFallback = "大模型翻译失败，已自动切换到 Google Translate"
    override val toastTranslateFailed = "翻译失败："
    override val toastTranslateError  = "翻译异常："

    override val settingsTitle          = "增强翻译"
    override val settingsBackendLabel   = "翻译后端"
    override val settingsSectionLLM     = "大模型配置"
    override val settingsSectionAuto     = "自动翻译"
    override val settingsSectionDebug   = "调试"
    override val settingsBackendGoogle  = "Google Translate"
    override val settingsBackendLLM     = "大模型（兼容 OpenAI）"
    override val settingsDefaultLanguage = "默认目标语言（点击设置）"
    override val settingsLanguageSaved   = "语言已保存"
    override val settingsLLMBaseUrl     = "大模型 Base URL"
    override val settingsLLMApiKey      = "大模型 API Key"
    override val settingsLLMModel       = "大模型名称"
    override val settingsCleanHtml      = "翻译前去除 HTML 标签"
    override val settingsCleanUrl       = "链接保护"
    override val settingsCleanUrlDesc   = "关闭（默认）：链接随原文交给翻译引擎，翻译后自动补回；开启：链接不参与翻译，原位还原"
    override val settingsCleanEmoji     = "翻译前去除 Emoji 表情"
    override val settingsAutoTranslateSelf = "翻译自己发送的消息"
    override val settingsAutoTranslateSelfDesc = "关闭（默认）：自动翻译时跳过自己发送的消息"
    override val settingsSupportedLanguages = "支持的语言："
    override val settingsCleaningLabel  = "文本清理"
    override val settingsCancel         = "取消"

    override val loadingText            = "翻译中..."

    // LLM API 测试相关
    override val settingsTestConnection = "测试连接"
    override val settingsFetchModels    = "获取可用模型"
    override val settingsTesting        = "正在测试连接..."
    override val settingsFetchingModels = "正在获取模型列表..."
    override val settingsTestSuccess    = "连接成功！"
    override val settingsTestFailed     = "连接失败："
    override val settingsModelsFetched  = "模型列表获取成功"
    override val settingsNoModelsFound  = "未找到可用模型"
    override val settingsSelectModel    = "选择模型"
    override val settingsTestError      = "测试失败："
    override val settingsFetchModelsError = "获取模型失败："
    override val settingsDialogError    = "显示对话框失败："
    override val settingsModelSet       = "模型已设置为："

    // Debug mode
    override val settingsDebugMode      = "调试模式"
    override val settingsDebugModeDesc  = "记录翻译详情到文件"
    override val settingsDebugClearLog  = "清除调试日志"
    override val settingsDebugLogPath   = "日志文件：/sdcard/Aliucord/translate.log"
    override val settingsDebugOn        = "调试已开启，日志："
    override val settingsDebugOff       = "调试已关闭"
    override val settingsLogCleared     = "日志已清除"
}
