package com.aliucord.plugins.translate.strings

object StringsEn : IStrings {
    override val pluginName           = "Translate Enhanced"

    override val actionTranslate      = "Translate message"
    override val actionShowOriginal   = "Show original"
    override val actionRetranslate    = "Retranslate message"
    override val actionToggleAuto     = "Auto translate this channel"
    override val actionDisableAuto    = "Disable auto translate"
    override val actionResumeAuto     = "Resume auto translate"

    override val toastTranslated      = "Message translated"
    override val toastAutoPaused      = "Auto translate paused due to failures. Tap to resume."
    override val toastAutoResumed     = "Auto translate resumed"
    override val toastAutoDisabled    = "Auto translate disabled"
    override val toastAutoBatchStart       = "Batch translating…"
    override val toastAutoBatchRequesting  = "Requesting translator ("
    override val toastAutoBatchRequestingEnd = " messages)…"
    override val toastAutoBatchDonePrefix  = "Batch done: "
    override val toastAutoBatchDoneSuffix  = " messages translated"
    override val toastBackendFallback = "LLM failed, falling back to Google Translate"
    override val toastTranslateFailed = "Translation failed: "
    override val toastTranslateError  = "Translation error: "

    override val settingsTitle          = "Translate Enhanced"
    override val settingsBackendLabel   = "Translation backend"
    override val settingsSectionLLM     = "LLM Configuration"
    override val settingsSectionAuto     = "Auto Translate"
    override val settingsSectionDebug   = "Debug"
    override val settingsBackendGoogle  = "Google Translate"
    override val settingsBackendLLM     = "LLM (OpenAI compatible)"
    override val settingsDefaultLanguage = "Default target language (tap to set)"
    override val settingsLanguageSaved   = "Language saved"
    override val settingsLLMBaseUrl     = "LLM Base URL"
    override val settingsLLMApiKey      = "LLM API Key"
    override val settingsLLMModel       = "LLM Model name"
    override val settingsCleanHtml      = "Clean HTML tags before translating"
    override val settingsCleanUrl       = "Link protection"
    override val settingsCleanUrlDesc   = "Off (default): links go to the translator and are restored if lost; On: links never reach the translator and are restored in place"
    override val settingsCleanEmoji     = "Clean emoji before translating"
    override val settingsAutoTranslateSelf = "Translate my own messages"
    override val settingsAutoTranslateSelfDesc = "Off (default): skip your own messages when auto-translating"
    override val settingsSupportedLanguages = "Supported languages:"
    override val settingsCleaningLabel  = "Text cleaning"
    override val settingsCancel         = "Cancel"

    override val loadingText            = "Translating..."

    // LLM API 测试相关
    override val settingsTestConnection = "Test Connection"
    override val settingsFetchModels    = "Fetch Available Models"
    override val settingsTesting        = "Testing connection..."
    override val settingsFetchingModels = "Fetching models..."
    override val settingsTestSuccess    = "Connection successful!"
    override val settingsTestFailed     = "Connection failed: "
    override val settingsModelsFetched  = "Models fetched successfully"
    override val settingsNoModelsFound  = "No models found"
    override val settingsSelectModel    = "Select a model"
    override val settingsTestError      = "Test failed: "
    override val settingsFetchModelsError = "Failed to fetch models: "
    override val settingsDialogError    = "Failed to show dialog: "
    override val settingsModelSet       = "Model set to: "

    // Debug mode
    override val settingsDebugMode      = "Debug Mode"
    override val settingsDebugModeDesc  = "Log translation details to file"
    override val settingsDebugClearLog  = "Clear Debug Log"
    override val settingsDebugLogPath   = "Log file: /sdcard/Aliucord/translate.log"
    override val settingsDebugOn        = "Debug ON \u2192 "
    override val settingsDebugOff       = "Debug OFF"
    override val settingsLogCleared     = "Log cleared"
}
