package com.aliucord.plugins.translate

import com.discord.api.commands.CommandChoice

val languageCodes = mapOf(
    "Afrikaans"                     to "af",
    "Albanian"                      to "sq",
    "Amharic"                       to "am",
    "Arabic"                        to "ar",
    "Armenian"                      to "hy",
    "Azerbaijani"                   to "az",
    "Basque"                        to "eu",
    "Belarusian"                    to "be",
    "Bengali"                       to "bn",
    "Bosnian"                       to "bs",
    "Bulgarian"                     to "bg",
    "Catalan"                       to "ca",
    "Chinese (Simplified)"         to "zh-CN",
    "Chinese (Traditional)"        to "zh-TW",
    "Chinese (Hong Kong)"          to "zh-HK",
    "Croatian"                      to "hr",
    "Czech"                         to "cs",
    "Danish"                        to "da",
    "Dutch"                         to "nl",
    "English"                       to "en",
    "Estonian"                      to "et",
    "Finnish"                       to "fi",
    "French"                        to "fr",
    "Georgian"                      to "ka",
    "German"                        to "de",
    "Greek"                         to "el",
    "Gujarati"                      to "gu",
    "Haitian Creole"                to "ht",
    "Hebrew"                        to "he",
    "Hindi"                         to "hi",
    "Hungarian"                     to "hu",
    "Icelandic"                     to "is",
    "Indonesian"                    to "id",
    "Irish"                         to "ga",
    "Italian"                       to "it",
    "Japanese"                      to "ja",
    "Javanese"                      to "jv",
    "Kannada"                       to "kn",
    "Kazakh"                        to "kk",
    "Khmer"                         to "km",
    "Korean"                        to "ko",
    "Kurdish"                       to "ku",
    "Lao"                           to "lo",
    "Latin"                         to "la",
    "Latvian"                       to "lv",
    "Lithuanian"                    to "lt",
    "Macedonian"                    to "mk",
    "Malay"                         to "ms",
    "Malayalam"                     to "ml",
    "Maltese"                       to "mt",
    "Maori"                         to "mi",
    "Marathi"                       to "mr",
    "Mongolian"                     to "mn",
    "Nepali"                        to "ne",
    "Norwegian"                     to "no",
    "Persian"                       to "fa",
    "Polish"                        to "pl",
    "Portuguese (Brazil)"           to "pt-BR",
    "Portuguese (Portugal)"         to "pt-PT",
    "Punjabi"                       to "pa",
    "Romanian"                      to "ro",
    "Russian"                       to "ru",
    "Serbian"                       to "sr",
    "Slovak"                        to "sk",
    "Slovenian"                     to "sl",
    "Somali"                        to "so",
    "Spanish"                       to "es",
    "Sundanese"                     to "su",
    "Swahili"                       to "sw",
    "Swedish"                       to "sv",
    "Tamil"                         to "ta",
    "Telugu"                        to "te",
    "Thai"                          to "th",
    "Turkish"                       to "tr",
    "Ukrainian"                     to "uk",
    "Urdu"                          to "ur",
    "Uzbek"                         to "uz",
    "Vietnamese"                    to "vi",
    "Welsh"                         to "cy",
    "Yiddish"                       to "yi",
    "Zulu"                          to "zu"
)

val languageCodeChoices: List<CommandChoice> =
    languageCodes.map { (name, code) -> CommandChoice(name, code) }
